version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models/saved:/app/models/saved
    depends_on:
      - mlflow

  mlflow:
    image: python:3.10-slim
    working_dir: /mlflow
    command: bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
